dist: xenial   # required for Python >= 3.7

os:
  - linux

language: python

matrix:
  include:
    - python: 3.6
    - python: 3.7
    - python: nightly
  allow_failures:
    - python: nightly

install:
  - make install

script:
  - flake8 .
  - mypy .
  - nosetests
  - coverage run --source=. -m unittest discover

after_success:
  - coveralls
